#!/usr/bin/env python3
"""
Génère CREDITS.md depuis assets/sounds/sounds.xlsx.

    python3 tools/gen-credits.py

Le tableur reste la source de vérité : on ajoute une ligne dedans quand on
ajoute un son, puis on relance ce script. CREDITS.md ne se modifie pas à la
main — il serait réécrit au prochain passage.

Écrit en Python et pas en Node comme le reste de tools/, pour une raison
simple : lire un .xlsx demande de décompresser un zip et de parser du XML, ce
que la bibliothèque standard de Python fait sans aucune dépendance. Ce script
tourne rarement, à la main ; la vérification qui tourne à CHAQUE build, elle,
est en Node dans tools/check-credits.mjs et ne lit que CREDITS.md.
"""

import os
import re
import sys
import zipfile
import xml.etree.ElementTree as ET

NS = '{http://schemas.openxmlformats.org/spreadsheetml/2006/main}'
XLSX = 'assets/sounds/sounds.xlsx'
OUT = 'CREDITS.md'
UNKNOWN_RE = re.compile(r'^\s*UNKNOWN', re.I)


def read_sheets(path):
    z = zipfile.ZipFile(path)
    shared = [''.join(t.text or '' for t in si.iter(NS + 't'))
              for si in ET.fromstring(z.read('xl/sharedStrings.xml')).findall(NS + 'si')]
    names = [s.get('name') for s in ET.fromstring(z.read('xl/workbook.xml')).iter(NS + 'sheet')]
    sheets = {}
    for i, name in enumerate(names, 1):
        try:
            root = ET.fromstring(z.read(f'xl/worksheets/sheet{i}.xml'))
        except KeyError:
            continue
        rows = []
        for row in root.iter(NS + 'row'):
            cells = {}
            for c in row:
                v = c.find(NS + 'v')
                cells[c.get('r')[0]] = ('' if v is None else
                                        (shared[int(v.text)] if c.get('t') == 's' else v.text))
            a, b = cells.get('A', '').strip(), cells.get('B', '').strip()
            if a.lower().endswith('.mp3'):
                rows.append((a, b))
        sheets[name] = rows
    return sheets


def author(url):
    m = re.search(r'/people/([^/]+)/', url) or re.search(r'/users/([^/?]+)', url)
    if not m:
        return '?'
    return re.sub(r'-\d{6,}$', '', m.group(1))


def sound_id(url):
    m = re.search(r'/sounds/(\d+)', url)
    return m.group(1) if m else 'lien'


def main():
    if not os.path.exists(XLSX):
        sys.exit(f'{XLSX} introuvable — lancer depuis la racine du dépôt.')
    sheets = read_sheets(XLSX)
    fx = sheets.get('FX', [])
    battle = sheets.get('Battle Music', [])
    bg = sheets.get('Background Music', [])

    def on_disk(folder, name):
        return os.path.exists(os.path.join(folder, name))

    L = []
    add = L.append
    add('# Credits — Primal Gambit')
    add('')
    add('> Every third-party asset shipped with this repository, with its author and source.')
    add('> Generated from `assets/sounds/sounds.xlsx` — the source of truth. Add a row there')
    add('> when you add a sound, then run `python3 tools/gen-credits.py`.')
    add('>')
    add('> Do not edit this file by hand; it gets overwritten.')
    add('')
    add('---')
    add('')
    add('## Sound effects — Freesound.org')
    add('')
    add(f'{len(fx)} files in `assets/sounds/fx/`. Each links to its Freesound page, where the')
    add('exact licence (CC0, CC BY, CC BY-NC or Sampling+) is stated by its author.')
    add('')
    add('**Check the licence on each page before reusing these files elsewhere:** several')
    add('Freesound licences require attribution by name, and CC BY-SA additionally forbids')
    add('adding restrictions — which this project\'s CC BY-NC-SA licence would do.')
    add('')
    add('| File | Author | Source |')
    add('|---|---|---|')
    unknown = []
    for name, url in fx:
        missing = '' if on_disk('assets/sounds/fx', name) else ' ⚠️ *(file not in repo)*'
        if not url or UNKNOWN_RE.match(url):
            unknown.append(name)
            add(f'| `{name}`{missing} | — | **unidentified** |')
        else:
            add(f'| `{name}`{missing} | {author(url)} | [{sound_id(url)}]({url}) |')
    add('')
    add('---')
    add('')
    add('## Music — Pixabay')
    add('')
    add('All music comes from [Pixabay](https://pixabay.com/) under the Pixabay Content')
    add('License, which permits free commercial and non-commercial use without attribution.')
    add('Credited here anyway, because the authors deserve it.')
    add('')
    for title, rows, folder in (
        ('Battle music — `assets/sounds/battle/`', battle, 'assets/sounds/battle'),
        ('Background music — `assets/sounds/music/`', bg, 'assets/sounds/music'),
    ):
        add(f'### {title}')
        add('')
        add('| File | Author |')
        add('|---|---|')
        for name, url in rows:
            missing = '' if on_disk(folder, name) else ' ⚠️ *(file not in repo)*'
            if not url or UNKNOWN_RE.match(url):
                unknown.append(name)
                add(f'| `{name}`{missing} | **unidentified** |')
            else:
                add(f'| `{name}`{missing} | [{author(url)}]({url}) |')
        add('')

    if unknown:
        add('---')
        add('')
        add('## ⚠️ Unidentified sources')
        add('')
        add('These files ship with the game but their origin is not recorded. Waveform')
        add('comparison against the sources listed above did not match them either, so the')
        add('rows are deliberately left blank rather than guessed.')
        add('')
        for name in unknown:
            add(f'- `{name}`')
        add('')
        add('If you know where they came from, fill the `source` column in')
        add('`assets/sounds/sounds.xlsx` and regenerate this file.')
        add('')

    add('---')
    add('')
    add('## Artwork')
    add('')
    add('All card illustrations, backgrounds, buttons, borders and comic panels were')
    add('generated with **ChatGPT / DALL·E** for this project. No EarthCore asset is used.')
    add('')
    add('## Font')
    add('')
    add('`assets/fonts/tt0524m_.ttf` — **Cinzel**, by Natanael Gama, released under the')
    add('[SIL Open Font License 1.1](https://openfontlicense.org/).')
    add('')
    add('## Code')
    add('')
    add('Written iteratively with **Claude** (Anthropic). See the README for the full story.')
    add('')
    add('---')
    add('')
    add('## About EarthCore')
    add('')
    add('Primal Gambit is a fan interpretation of *EarthCore: Shattered Elements* (Tequila')
    add('Games, 2014). It is not affiliated with or endorsed by its rights holders, contains')
    add('none of its assets, and is distributed free of charge.')

    open(OUT, 'w', encoding='utf-8').write('\n'.join(L) + '\n')
    total = len(fx) + len(battle) + len(bg)
    print(f'{OUT} écrit — {total} fichiers ({len(fx)} FX, {len(battle)} battle, {len(bg)} bg)'
          + (f', {len(unknown)} sans source' if unknown else ''))


if __name__ == '__main__':
    main()
